// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC36QGj3FRsMa4qomCOSVAA5DpnJU62kMU',
    appId: '1:873102526889:web:459167752edf3695015cb8',
    messagingSenderId: '873102526889',
    projectId: 'jetcare-f4e39',
    authDomain: 'jetcare-f4e39.firebaseapp.com',
    storageBucket: 'jetcare-f4e39.appspot.com',
    measurementId: 'G-VE6C9EWW39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlnIf4aQA1LaQv1Ztl4LX0BAQjuzajr5o',
    appId: '1:873102526889:android:2175a1371985d6b3015cb8',
    messagingSenderId: '873102526889',
    projectId: 'jetcare-f4e39',
    storageBucket: 'jetcare-f4e39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGZIJomhIOiJI9giOqHhpOtw7S0caHKGk',
    appId: '1:873102526889:ios:5cb3cf20dd87881e015cb8',
    messagingSenderId: '873102526889',
    projectId: 'jetcare-f4e39',
    storageBucket: 'jetcare-f4e39.appspot.com',
    iosClientId: '873102526889-c2uaueul1660p29qsese64k1j264hp09.apps.googleusercontent.com',
    iosBundleId: 'com.jetcareeg.jetcare',
  );
}
